version: "3"

services:
  reverse-proxy:
    build: 'reverse-proxy/'
    restart: always
    container_name: 'secretsanta_reverse_proxy'
    image: secretsanta/reverse-proxy:latest
    depends_on: ["webapp", "backend", "database"]
    networks: [secretsanta]
    ports: [80:80]
    volumes:
      - /root/certs-data/:/data/letsencrypt/
  webapp:
    build: "webapp/"
    restart: always
    container_name: secretsanta_webapp
    image: secretsanta/webapp:latest
    networks: [secretsanta]
  backend:
    build: "core/"
    restart: always
    container_name: secretsanta_backend
    image: secretsanta/backend:latest
    depends_on: [database]
    environment:
      DB_USER: "${DB_USER}"
      DB_PASS: "${DB_PASS}"
      DB_NAME: "${DB_NAME}"
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
      PGSQL_CS: "host=database user=${DB_USER} password=${DB_PASS} dbname=${DB_NAME} port=5432"
      ALLOWED_HOSTS: "${ALLOWED_HOSTS}"
      COOKIE_SECRET: "${COOKIE_SECRET}"
      GIN_MODE: "${GIN_MODE}"
    networks: [secretsanta]
  database:
    image: postgres
    restart: always
    container_name: secretsanta_database
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    networks: [secretsanta]
    volumes:
      - database_data:/var/lib/postgresql/data

networks:
  secretsanta:
    driver: bridge

volumes:
  database_data: