openapi: '3.0.2'
info:
  title: Secret Santa API
  version: '1.0'
servers:
  - url: https://localhost/v1

components:
  schemas:
    StatusResultTo:
      type: object
      properties:
        property:
          type: integer
    ExceptionResponseTo:
      type: object
      properties:
        property:
          type: integer
    PlayerResponseTo:
      type: object
      properties:
        property:
          type: integer
    GetFullGameResponseTo:
      type: object
      properties:
        property:
          type: integer
    GetBasicGameResponseTo:
      type: object
      properties:
        property:
          type: integer
    DrawGameResponseTo:
      type: object
      properties:
        property:
          type: integer
    DrawGameTo:
      type: object
      properties:
        property:
          type: integer
    AddExceptionTo:
      type: object
      properties:
        property:
          type: integer
    RegisterLoginPlayerPasswordResponseTo:
      type: object
      properties:
        property:
          type: integer
    RegisterLoginPlayerPasswordTo:
      type: object
      properties:
        property:
          type: integer
    AddRemovePlayerTo:
      type: object
      properties:
        property:
          type: integer
    CreateGameTo:
      type: object
      properties:
        property:
          type: integer
    CreateGameResponseTo:
      type: object
      properties:
        property:
          type: integer
paths:
  /createNewGame:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateGameTo'
      responses:
        '200':
          description: OK